name: Build Platform Racing 4 Game Server
run-name: ${{ github.actor }} is building a new version of Platform Racing 4 Game Server 🚀
on:
  push:
    paths:
      - game-server/**
permissions:
  packages: write

jobs:
  build:
    name: Build Game Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Test
        run: |
          cd game-server
          go test .
      - name: Build Image
        run: |
          cd game-server
          docker build -t pr4 --file Dockerfile .
          if [ "$GITHUB_REF_NAME" == "main" ] || [ "$GITHUB_REF_NAME" == "release" ]; then
            tag="$(date +%F-%H-%M)-$GITHUB_REF_NAME-$GITHUB_SHA"
            docker tag pr4 ghcr.io/jacob-grahn/platform-racing-4-game-server:latest
            docker push ghcr.io/jacob-grahn/platform-racing-4-game-server:latest
            docker tag pr4 ghcr.io/jacob-grahn/platform-racing-4-game-server:$tag
            docker push ghcr.io/jacob-grahn/platform-racing-4-game-server:$tag
          fi
