name: Build Platform Racing 4 API
run-name: ${{ github.actor }} is building a new version of Platform Racing 4 API 🚀
on:
  push:
    paths:
      - api/**
permissions:
  packages: write

jobs:
  build-api:
    name: Build API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Test
        run: |
          cd api
          go test ./...
      - name: Build Image
        run: |
          cd api
          docker build -t pr4 --file Dockerfile .
          if [ "$GITHUB_REF_NAME" == "main" ] || [ "$GITHUB_REF_NAME" == "release" ]; then
            tag="$(date +%F-%H-%M)-$GITHUB_REF_NAME-$GITHUB_SHA"
            docker tag pr4 ghcr.io/jacob-grahn/platform-racing-4-api:latest
            docker push ghcr.io/jacob-grahn/platform-racing-4-api:latest
            docker tag pr4 ghcr.io/jacob-grahn/platform-racing-4-api:$tag
            docker push ghcr.io/jacob-grahn/platform-racing-4-api:$tag
          fi
